import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ProvidersHeroUI } from "./providers";
import NavbarComp from "@/componests/shared/NavbarComp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Restobar \"La Hermandad\"",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-screen`}
      >
        <ProvidersHeroUI>
          <NavbarComp label={"La Hermandad"}/>
          {children}
        </ProvidersHeroUI>
      </body>
    </html>
  );
}
